
-- I. Movies

-- 1.
SELECT title, name
FROM MOVIEEXEC JOIN MOVIE ON CERT# = PRODUCERC#
WHERE PRODUCERC# = (SELECT PRODUCERC# FROM MOVIE WHERE TITLE = 'Star Wars');

-- 2.
SELECT DISTINCT name
FROM MOVIEEXEC JOIN MOVIE ON CERT# = PRODUCERC#
JOIN STARSIN ON TITLE = MOVIETITLE
WHERE STARNAME = 'Harrison Ford';

-- 3.
SELECT DISTINCT name, starname
FROM STUDIO JOIN MOVIE ON NAME = STUDIONAME
JOIN STARSIN ON TITLE = MOVIETITLE
ORDER BY name ASC

-- 4.
SELECT starname, networth, title
FROM MOVIE INNER JOIN (SELECT NAME, NETWORTH, CERT# FROM MOVIEEXEC WHERE NETWORTH >= ALL (SELECT NETWORTH FROM MOVIEEXEC)) movieExec 
			ON PRODUCERC# = CERT#
INNER JOIN STARSIN ON TITLE = MOVIETITLE;

-- 5.
SELECT name, movietitle
FROM MOVIESTAR LEFT JOIN STARSIN ON NAME = STARNAME
LEFT JOIN MOVIE ON MOVIETITLE = TITLE
WHERE movietitle IS NULL






-- II. PC

-- 1.
SELECT maker, pr.model, type
FROM product AS pr LEFT JOIN (
	SELECT model FROM laptop
	UNION
	SELECT model FROM printer
	UNION
	SELECT model FROM pc) allProducts ON pr.model = allProducts.model
WHERE allProducts.model IS NULL;

-- 2.
SELECT maker 
FROM product JOIN laptop ON product.model = laptop.model 
	
INTERSECT
	
SELECT maker
FROM product JOIN printer on product.model = printer.model;


-- 3.
SELECT DISTINCT l1.hd
FROM laptop as l1 INNER JOIN laptop AS l2 ON l1.hd = l2.hd
WHERE l1.code < l2.code

-- 4.
SELECT *
FROM pc LEFT JOIN product ON pc.model = product.model
WHERE product.model = NULL;






-- III. Ships

-- 1.
SELECT *
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS;

-- 2.
SELECT * 
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.NAME IS NOT NULL OR CLASSES.CLASS IN (SELECT NAME FROM SHIPS);

-- 3.
SELECT country, name
FROM CLASSES INNER JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP WHERE OUTCOMES.BATTLE IS NULL 
ORDER BY country, name

-- 4.
SELECT name AS ShipName
FROM SHIPS INNER JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE LAUNCHED = 1916 AND NUMGUNS >= 7;

-- 5.
SELECT ships.name, battle, date
FROM SHIPS INNER JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
INNER JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE RESULT = 'sunk'
ORDER BY battle;

-- 6.
SELECT name, displacement, launched
FROM SHIPS INNER JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.NAME = SHIPS.CLASS;

-- 7.
SELECT CLASSES.*
FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
WHERE SHIPS.NAME IS NULL;

-- 8.
SELECT name, displacement, numguns, result
FROM SHIPS INNER JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
INNER JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.BATTLE = 'North Atlantic';
